### ISSUE TITLE
Bang Syntax Highlighting Issues

### ISSUE THREAD

**Issue by raiguard** [will-shaw/ws-rainmeter#6]
Good day. I really appreciate this extension, as VSCode is my favorite text editor and I don't have the expertise to write a Rainmeter extension myself. Good work!

Anyway, there is an issue with bang syntax highlighting:

![2019-01-11 21_00_50-sb1background ini - rainmeter workspace - visual studio code](https://user-images.githubusercontent.com/3515394/51069040-86372b00-15e4-11e9-9496-9d2bdb4d74b9.png)
![2019-01-11 21_01_28-sb1background ini - rainmeter workspace - visual studio code](https://user-images.githubusercontent.com/3515394/51069041-86372b00-15e4-11e9-9355-e7a49032d876.png)

As you can see, the syntax highlighting for bangs only works if there is a space between the bracket and the bang itself. Even in your preview image, this is not the case, which makes me believe it is a bug.

Thanks for your time!

**Comment by will-shaw** [comment]
Thanks, @raiguard, I haven't spent much time writing for Rainmeter lately so didn't notice it.

 I've updated it with a temporary workaround to which solves the syntax highlighting for the contents of the bang, but now the bang square bracket character is not highlighted. 

I figure this is the least annoying bug of the two, so I've added this for now until I get a bit more time to fix it properly :)

**Comment by raiguard** [comment]
Thanks, sorry I never replied. If I can figure out the syntax, I'll try to help out (I've tried making grammars before but could never quite wrap my head around it).
